CREATE TABLE User_SmartLifeStorage(
  fullDate NUMERIC,
  date TEXT,
  week TEXT,
  month INTEGER,
  action TEXT,
  actiontip TEXT,
  subcontent TEXT,
  content TEXT,
  contentsmall TEXT,
  colorBot INTEGER,
  colorTop INTEGER,
  icon TEXT,
  blankL TEXT,
  buttonL TEXT,
  type TEXT,
  showline TEXT,
  sdate NUMERIC,
  stime TEXT,
  showtitle TEXT,
  uid TEXT
);
CREATE TABLE Ignore_SmartLifeStorage(
  fullDate NUMERIC,
  date TEXT,
  week TEXT,
  month INTEGER,
  action TEXT,
  actiontip TEXT,
  subcontent TEXT,
  content TEXT,
  contentsmall TEXT,
  colorBot INTEGER,
  colorTop INTEGER,
  icon TEXT,
  blankL TEXT,
  buttonL TEXT,
  type TEXT,
  showline TEXT,
  sdate NUMERIC,
  stime TEXT,
  showtitle TEXT,
  uid TEXT,
  CISNum TEXT
);
CREATE TABLE TodayNotified_SmartLifeStorage(
  fullDate NUMERIC,
  date TEXT,
  week TEXT,
  month INTEGER,
  action TEXT,
  actiontip TEXT,
  subcontent TEXT,
  content TEXT,
  contentsmall TEXT,
  colorBot INTEGER,
  colorTop INTEGER,
  icon TEXT,
  blankL TEXT,
  buttonL TEXT,
  type TEXT,
  showline TEXT,
  sdate NUMERIC,
  stime TEXT,
  showtitle TEXT,
  uid TEXT
);
