CREATE TABLE User_AdvertingStorage(
  ID INTEGER primary key autoincrement,
  ADV_ID TEXT,
  ADV_KIND TEXT,
  ADV_DESCRIPTION TEXT,
  ADV_SHOW TEXT,
  ADV_BEGINDATE TEXT,
  ADV_ENDDATE TEXT,
  ADV_PICPATH TEXT,
  ADV_LOCALPICPATH TEXT,
  ADV_AREACODE TEXT,
  ADV_URLTYPE TEXT,
  ADV_URL TEXT
);